# Generated by Django 5.2.1 on 2025-06-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_studyschedule_end_time_studyschedule_is_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyschedule',
            old_name='date',
            new_name='study_date',
        ),
        migrations.RemoveField(
            model_name='studyschedule',
            name='hours',
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='study_hours',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyschedule',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
