# Generated by Django 5.2.1 on 2025-06-27 09:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_remove_useravailability_daily_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyschedule',
            name='study_date',
        ),
        migrations.AddField(
            model_name='studyschedule',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
